[package]
name = "gameapi-api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.11"
serde_json = "1.0"
serde_yaml = "0.8"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
xmltojson = "0"
futures = "0.3"
either = { version = "1.6.1", features = ["serde"] }
